### ISSUE TITLE
Error while writing out exception

### ISSUE THREAD

**Issue by zonk0101** [aerickson/OctoPrint_Signal-Notifier#1]
Hi,

I get an Error while the Plugin is trying to write out an exception :/
I registered my signal-user under the wrong unix-user, but, the Plugin, doesn't write out any error-information.

2018-12-08 22:43:31,576 - octoprint.plugin - ERROR - Error while calling plugin signalnotifier
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 225, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  **File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_signalnotifier/__init__.py", line 70, in on_event
    self._logger.exception("Signal notification error: %s: %s" % (str(e)), osstdout)
TypeError: not enough arguments for format string**

**Comment by aerickson** [comment]
Sorry about that. I found the bug and have pushed a fix. Just update the plugin by going to Settings > Software Update and clicking 'Update All' and then restart Octoprint.

If you registered under the wrong unix user, you can copy the ~/.config/signal directory to the correct user's homedir, fix the permissions, and everything should work.

**Comment by zonk0101** [comment]
Thanks for reacting so fast!
I already fixed my wrong-user problem :)
But before, I fiddled around with this line, it looks like the parameters are not compatible, also:
"%s" % (osstdout)
and
"%s" % (str(e))
didn't work, same error
I have no practice with python, could it be one of those 2.7 vs 3 problems?

**Comment by aerickson** [comment]
Just another bug. :) On an error, that variable never gets defined. 

I've pushed a fix.

**Comment by zonk0101** [comment]
Hi again,

i retested my problem, it is solved now, as I get correct log-output:
2018-12-10 09:15:02,489 - octoprint.plugins.signalnotifier - ERROR - The sender ('+xxxxxxx') is not registered!
2018-12-10 09:15:02,490 - octoprint.plugins.signalnotifier - ERROR - Command: '/usr/local/bin/signal-cli -u +xxxxxxx listIdentities'
2018-12-10 09:15:02,491 - octoprint.plugins.signalnotifier - ERROR - Command output: 'User is not registered.'

But also, something wen't wrong. :/
With only "signal-cli" as the Path, it doesn't work anymore, I had to change to the full-path.
2018-12-10 16:04:48,747 - octoprint.plugins.signalnotifier - ERROR - The path to signal-cli ('signal-cli') doesn't point at an executable!

I think, this is not what you expected.

A big fat thank you for providing this plugin, this is a huge printer-upgrade for me :D

**Comment by aerickson** [comment]
Full path is intentional. The field has always said full path, but just
'signal-cli' worked because I was using shell=True in the subprocess call.
Using shell=True in subprocess calls is considered a security risk (someone could append a malicious command and wipe out parts of the filesystem or other things). It is confusing
that the default is just signal-cli (picking a good default for full path
is hard)... Perhaps should be empty. I can look at searching in PATH for
signal-cli also (what shell=True ends up doing).

The error message indicates you have a sender address that's not
registered. Follow the signal-cli docs to link or register.
