### ISSUE TITLE
Do I need more than the plugin?

### ISSUE THREAD

**Issue by Budge72** [aerickson/OctoPrint_Signal-Notifier#2]
I installed the notifier using the Octoprint Plugin Manager.  But nothing is happening at the end of my prints.  Am I supposed to manually install Signal-cli on my raspberry or Windows 10?  If so, how?

**Comment by aerickson** [comment]
Yes, the plugin page and github mention that it's required.

https://plugins.octoprint.org/plugins/signalnotifier/
https://github.com/aerickson/OctoPrint_Signal-Notifier#configuration

Directions for installing signal-cli are on it's homepage. I give some notes on the github.

**Comment by aerickson** [comment]
I've clarified the requirement in the README in this repo and opened https://github.com/OctoPrint/plugins.octoprint.org/pull/256 to hopefully make this clearer.

Did you install via the in-app plugin manager?

Thanks.

**Comment by Budge72** [comment]
Hi.  I'm a complete noob to github, so the language is difficult for me to follow.
"You can build signal-cli yourself, or use the provided binary files, which should work on Linux, macOS and Windows. For Arch Linux there is also a package in AUR. You need to have at least JRE 7 installed, to run signal-cli."

I'm not sure what this means, and on what device I'm supposed to do it on.  I did the install in Octoprint via the plugin manager only.  Will you please tell me what I need to do next.
Thank you.

**Comment by aerickson** [comment]
What OS are you running OctoPrint on?

**Comment by Budge72** [comment]
Raspberry Pi 3B+.  I am monitoring Octoprint using my browser in Windows 10.

**Comment by aerickson** [comment]
OK, what OS are you running on the RPI? 

If it's Octopi/Raspbian, which is a flavor of Linux called Debian, these directions should work. https://github.com/AsamK/signal-cli/wiki/HowToUbuntu

**Comment by Budge72** [comment]
I really appreciate your help.  Unfortunately, the only experience I have with my RPI or Linux was copying the the Octopi files over to a microSD card, then putting that in the RPI.  I only connect to the RPI via octoprint through my web browser.  I don't even have an hdmi cable for it.  I read online that I can use Putty to access the OS from within Windows.  I will give that a try.  Thank you.

**Comment by aerickson** [comment]
Aaaah fun. Yeah, it's going to be a learning experience for you. :)

Yeah, you should be able to ssh to the RPI with putty. Happy to help if you get stuck.

**Comment by aerickson** [comment]
Closing this for now, but feel free to reply if you need any help in your journey. :)
