### ISSUE TITLE
[DOCS] You can now send to self

### ISSUE THREAD

**Issue by darkporpoise** [aerickson/OctoPrint_Signal-Notifier#22]
Signal (and signal-cli) now allow sending messages to yourself which appear as "Note to Self" in the app.

The process for me was:

1) Android app already registered with my number on my phone (i.e. master device)
2) Install [signal-cli](https://github.com/AsamK/signal-cli/wiki/HowToUbuntu) on OctoPrint. **But do NOT "register"**
3) Run `signal-cli link -n "OctoPrint"` on Octoprint to generate a _tsdevice_ [link](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning))
4) Copy the _tsdevice_ link to [generate](https://www.qr-code-generator.com) a QR code.
5) Back in the app on your phone **_Settings --> Linked devices --> +_**
6) Scan QR code and accept link
7) Send yourself a message with _signal-cli_ `signal-cli -u +447555000555 send -m "My first message from the CLI" +447555000555`
8) Profit

**Comment by darkporpoise** [comment]
Major downside is that you don't get a notification on the app as it comes through as Note-to-self.

**Comment by aerickson** [comment]
Thanks! I'll get this into the docs.

**Comment by aerickson** [comment]
Fixed by #27.
