### ISSUE TITLE
Feature request: send message at error

### ISSUE THREAD

**Issue by Protoncek** [aerickson/OctoPrint_Signal-Notifier#25]
Hello!
I’m using this great plugin with joy, i do however one question: is it possible that we would receive a message when something is wrong during print? I mean: if octoprint receives major error from printer stops printing and sends M112 to the printer (like MINTEMP error or similar). It would be great if we would receive a message on signal, too...

**Comment by aerickson** [comment]
Great idea. We'd just have to add handling of that particular type of event at https://github.com/aerickson/OctoPrint_Signal-Notifier/blob/master/octoprint_signalnotifier/__init__.py#L75.

**Comment by Protoncek** [comment]
Well, i came to this thought because i have problems with my printer lately. I’m printing covid-19 face masks (prusa model) intensively and it seems that i have problems with my bed thermistor, because a few of my prints stopped suddenly because of “mintemp bed” error. 
I’m not exactly a skilled programmer, my knowledge is more or less limited to bascom for AVR’s and basci C for arduino’s, so unfortunately i can’t be of any help here.
