### ISSUE TITLE
Feature request: send image of print when completed

### ISSUE THREAD

**Issue by rtideas** [aerickson/OctoPrint_Signal-Notifier#9]
Would be nice to get an image sent of the print as well when it is finished. 

I read Signal does allow for images, but don’t know the complexities.

Previously, I used an email plugin and it was a charm (but a bear to set up). But no longer supported or readily available for the latest OctoPrint versions.

Thanks.

**Comment by beeepus** [comment]
Hi,
This is my patch on current master branch that will add snapshot attachment.
It use octoprint.timelapse so no dependence is needed for this.
It has no error handling so if it doesn't gets a snapshot it probably won't send any message at all.
It doesn't handle image rotation nor flipping. Workaround just rotate your phone =O) 
it doesn't delete the image file after so keep that in mind.

How to apply the patch.
Get a terminal to octoprint
change dir to octoprint_signalnotifier. most likely /home/pi/oprint/lib/python2.7/site-packages/octoprint_signalnotifier/
patch -p1 < octoprint_signalnotifier-snapshot.txt
restart octoprint

You will have the option to enable/disable in the Signal Notifier Configuration settings.
     
[octoprint_signalnotifier-snapshot.txt](https://github.com/aerickson/OctoPrint_Signal-Notifier/files/2729446/octoprint_signalnotifier-snapshot.txt)

Cheers,

**Comment by aerickson** [comment]
Sweet. Thanks. :)

 I'll try to get this in a branch and merged soon.

**Comment by aerickson** [comment]
Merged. Thanks @beepus!
